name: Build

on:
  push:
    branches: [ master, dev ]

jobs:

  validate_new_version:
    name: Validate new version
    runs-on: ubuntu-latest
    outputs:
      planned_version: ${{ steps.planned_version.outputs.planned_version }}
      tag_hash: ${{ steps.tag_exists.outputs.tag_exists }}
      can_build: ${{ steps.can_create.outputs.can_create }}

    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check if .version file exists
      id: version_file_exists
      run: |
        if [[ -f .version ]]; then 
          echo "::set-output name=version_file_exists::true"
        else 
          echo "::set-output name=version_file_exists::false" 
        fi

    - name: Read out .version file
      if: steps.version_file_exists.outputs.version_file_exists == 'true'
      id: planned_version
      run: echo "::set-output name=planned_version::$(cat .version)"

    - name: Display planned version
      id: display_planned_version
      run: |
        echo "::debug::Planned version: ${{steps.planned_version.outputs.planned_version}}"

    - name: Lookup planned tag
      id: lookup_tag
      run: |
        URL="https://api.github.com/repos/${{github.repository}}/git/refs/tags/${{steps.readversionfile.outputs.desiredversion}}"
        OUTFILE=".tag_hash"
        curl -s -X GET -H 'authorization: Bearer ${{secrets.GITHUB_TOKEN}}' --url "${URL}" | jq .object.sha | tee "${OUTFILE}"
        echo "::set-output name=tag_hash::$(cat "${OUTFILE}")"
    
    - name: Check if planned tag doesn't exist yet
      id: tag_exists
      if: steps.lookup_tag.outputs.tag_hash == 'null'
      run: |
        echo "::set-output name=tag_exists::false"

    - name: Define if can create a new version
      id: can_create
      if: steps.tag_exists.outputs.tag_exists == 'false'
      run: |
        echo "::set-output name=can_create::true"

  build:
    name: Build, Test, Packages
    runs-on: ubuntu-latest
    if: needs.validate_new_version.outputs.can_create == 'true'
    
    env:
      PLANNED_VERSION=${{ needs.validate_new_version.outputs.planned_version }}

    steps:

    - name: Build
      id: make_build
      run: make build

    - name: Test
      id: make_test
      run: make test

    - name: Generate changelog
      id: generate_changelog
      if: steps.tag_exists.outputs.tag_exists == 'false'
      shell: bash
      run: |
        described=$(git describe --tags || git rev-list --max-parents=0 HEAD)
        described_parts=( ${described//-/ } )
        current_tag=${described_parts[0]}
        
        changelog_filename=".changelog"
        release_changelog_filename=".release_changelog"
        echo "current_tag=${current_tag}"

        echo "Listing current changes..."
        git log --pretty=oneline --format='%w(1000)* %cd %an <%ae>%n%w(60,0,2)- %s%n' --date="format:%a %b %d %Y" "$current_tag"..HEAD | tee "${changelog_filename}"
        git log --pretty=oneline --format='%w(1000)**%cd %an <%ae>**%n%w(60,0,2)- %s%n' --date="format:%a %b %d %Y" "$current_tag"..HEAD | tee "${release_changelog_filename}"
        
        echo "Changelog file..."
        cat .changelog

        echo "Preparing a GitHub Release Changelog"
        cat << EOF > "${release_changelog_filename}"
        Automatically generated release with assets.

        Changelog:
        $(cat "${release_changelog_filename}")
        EOF

        echo "::set-output name=changelog_filename::${changelog_filename}"
        echo "::set-output name=release_changelog_filename::${release_changelog_filename}"

    - name: Display changelog
      run: echo "${{ steps.generate_changelog.outputs.changelog }}"

    - name: Setup RPM Build environment
      id: setup_rpmbuild_env
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install rpm

        make build
        make compress

        # rpmdev-setuptree
        mkdir /home/runner/rpmbuild
        mkdir -pv /home/runner/rpmbuild/BUILD
        mkdir -pv /home/runner/rpmbuild/BUILDROOT
        mkdir -pv /home/runner/rpmbuild/RPMS
        mkdir -pv /home/runner/rpmbuild/SOURCES
        mkdir -pv /home/runner/rpmbuild/SPECS
        mkdir -pv /home/runner/rpmbuild/SRPMS
        
        cp -v ".rpm/rsaenc.spec.tpl" /home/runner/rpmbuild/SPECS
        mv -v /home/runner/rpmbuild/SPECS/rsaenc.spec.tpl /home/runner/rpmbuild/SPECS/rsaenc.spec
        
        sed -i"" \
          -e "s/__VERSION__/${PLANNED_VERSION}/" \
          -e "s/__SOURCE_TARGZ_FILENAME__/rsaenc-${PLANNED_VERSION}.tar.gz/" \
          /home/runner/rpmbuild/SPECS/rsaenc.spec
        
        cat "${{steps.generate_changelog.outputs.changelog_filename}}" >> /home/runner/rpmbuild/SPECS/rsaenc.spec
        cat -n /home/runner/rpmbuild/SPECS/rsaenc.spec

        cp -v "rsaenc-${PLANNED_VERSION}.tar.gz" /home/runner/rpmbuild/SOURCES

    - name: Build RPM package
      id: build_rpm_package
      shell: bash
      run: |
        cd /home/runner
        rpmbuild -v -ba "rpmbuild/SPECS/rsaenc.spec"

    - name: Verify RPM package
      id: verify_rpm_package
      run: |
        ls -la /home/runner/rpmbuild/RPMS/x86_64/rsaenc-${PLANNED_VERSION}-1.x86_64.rpm
        echo "::set-output name=path_to_rpm_file::/home/runner/rpmbuild/RPMS/x86_64/rsaenc-${PLANNED_VERSION}-1.x86_64.rpm"
        echo "::set-output name=rpm_filename::rsaenc-${PLANNED_VERSION}-1.x86_64.rpm"

    - name: Setup DEB Build environment
      id: setup_debbuild_env
      shell: bash
      run: |
        size="$(stat --printf="%s" rsaenc)"

        mkdir -v /home/runner/debbuild
        mkdir -v /home/runner/debbuild/DEBIAN
        mkdir -vp /home/runner/debbuild/usr/bin
        mkdir -vp "/home/runner/debbuild/usr/share/doc/rsaenc-${PLANNED_VERSION}"

        cp -v ".deb/control.tpl" /home/runner/debbuild/DEBIAN
        mv -v /home/runner/debbuild/DEBIAN/control.tpl /home/runner/debbuild/DEBIAN/control
        
        cp -v "rsaenc-${PLANNED_VERSION}/rsaenc" /home/runner/debbuild/usr/bin/
        cp -v "rsaenc-${PLANNED_VERSION}/README.md" "/home/runner/debbuild/usr/share/doc/rsaenc-${PLANNED_VERSION}"

        sed -i"" \
          -e "s/__VERSION__/${PLANNED_VERSION}/" \
          -e "s/__SIZE__/${size}/" \
          /home/runner/debbuild/DEBIAN/control
        
        cat -n /home/runner/debbuild/DEBIAN/control

    - name: Build DEB package
      id: build_deb_package
      shell: bash
      run: |
        cd /home/runner
        dpkg-deb --build debbuild
      
        mv debbuild.deb rsaenc-${PLANNED_VERSION}_amd64.deb

    - name: Verify DEB package
      id: verify_deb_package
      run: |
        ls -la "/home/runner/rsaenc-${PLANNED_VERSION}_amd64.deb"
        echo "::set-output name=path_to_deb_file::/home/runner/rsaenc-${PLANNED_VERSION}_amd64.deb"
        echo "::set-output name=deb_filename::rsaenc-${PLANNED_VERSION}_amd64.deb"

    - name: Install DEB package
      id: install_deb_package
      run: |
        sudo dpkg -i "${{steps.verify_deb_package.outputs.path_to_deb_file}}"
        ls -la /usr/bin/rsaenc
        ls -la /usr/share/doc/rsaenc*
        rsaenc -h

    - name: Create a new tag
      run: |
        curl --request POST --url https://api.github.com/repos/${{ github.repository }}/git/tags \
        -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        -H 'content-type: application/json' \
        --data '{"tag": "${{steps.readversionfile.outputs.desiredversion}}",
          "message": "Pipeline build tag",
          "object": "${{ github.sha }}",
          "type": "commit",
          "tagger": {
            "name": "Alice from Wonderland",
            "email": "noreply@localhost.localdomain",
            "date": "${{steps.timestamp.outputs.timestamp}}"
          }'

    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{steps.readversionfile.outputs.desiredversion}}
        release_name: v${{steps.readversionfile.outputs.desiredversion}}
        body_path: ${{steps.generate_changelog.outputs.release_changelog_filename}}
        draft: false
        prerelease: false

    - name: Upload a Release Asset (rsaenc)
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./rsaenc-${{ steps.readversionfile.outputs.desiredversion }}/rsaenc
        asset_name: rsaenc
        asset_content_type: application/octet-stream

    - name: Upload a Release Asset (RPM package)
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.verify_rpm_package.outputs.path_to_rpm_file }}
        asset_name: ${{ steps.verify_rpm_package.outputs.rpm_filename }}
        asset_content_type: application/octet-stream

    - name: Upload a Release Asset (DEB package)
      uses: actions/upload-release-asset@v1.0.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.verify_deb_package.outputs.path_to_deb_file }}
        asset_name: ${{ steps.verify_deb_package.outputs.deb_filename }}
        asset_content_type: application/octet-stream

    - name: Upload RPM package to repository
      id: upload_rpm_to_repository
      run: |
        export RSYNC_PASSWORD="${{ secrets.RSYNC_PASSWORD }}"
        rsync \
          -raz -vv \
          --port "${{ secrets.RSYNC_PORT }}" \
          "${{steps.verify_rpm_package.outputs.path_to_rpm_file}}" \
          ${{ secrets.RSYNC_USERNAME }}@${{ secrets.RSYNC_HOSTNAME }}::${{ secrets.RSYNC_PATH_RPM_EL7 }}

    - name: Upload DEB package to repository
      id: upload_deb_to_repository
      run: |
        export RSYNC_PASSWORD="${{ secrets.RSYNC_PASSWORD }}"
        rsync \
          -raz -vv \
          --port "${{ secrets.RSYNC_PORT }}" \
          "${{steps.verify_deb_package.outputs.path_to_deb_file}}" \
          ${{ secrets.RSYNC_USERNAME }}@${{ secrets.RSYNC_HOSTNAME }}::${{ secrets.RSYNC_PATH_DEB }}
