name: Build and test

on:
  push:
    branches: [ '*' ]

jobs:

  build:
    name: Test branch
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: make build

    - name: Test
      run: make test
