name: Validate PR

on:
  pull_request:
    branches: [ master ]

jobs:

  validate_pr:
    name: Validate PR
    runs-on: ubuntu-latest

    outputs:
      job_status: ${{ job.status }}

    needs:
      - build_and_test
      - validate_new_version

    steps:

    - name: Check if can create a new version
      run: echo "Passed"

    - name: Check if build and test passed successfully
      run: echo "Passed"
